name: ubuntu-latest

on:
  push:
    branches: [ main ]
    paths:
      - '**.yml'
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**.ts'
  
  pull_request:
    branches: [ main ]
    paths:
      - '**.yml'
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**.ts'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies by apt and pip
        run: |
          sudo apt --fix-broken install
          sudo apt update -y
          sudo apt install -y ninja-build
          pip install conan cmake
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.0
          modules: qtmultimedia
          aqtversion: '>=3.1.0'
          py7zrversion: '>=0.20.2'
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Conan installation
        run: |
          conan profile detect --force
          
          mkdir build
          
          conan install ./conanfile_ci.txt  \
          -of build                         \
          --build=missing

      - name: CMake configuration
        run: |
          cd build
          
          cmake .. Ninja \
          -D CMAKE_BUILD_TYPE=Release \
          -D CMAKE_PREFIX_PATH=${{ env.Qt6_DIR }} \
          -D CMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
          
      - name: Build
        run: cmake --build build
