name: ubuntu-latest

on:
  push:
    branches: [ main ]
    paths:
      - '**.yml'
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**.ts'
  
  pull_request:
    branches: [ main ]
    paths:
      - '**.yml'
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**.ts'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies by apt
        run: |
          sudo apt install \
          cmake ninja-build \
          libtag1-dev \
          libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev
          
      - name: Install Qt
        env:
          TP_QT_VERSION: 6.2.2
          TP_AQT_VERSION: ">=2.0.5"
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ env.TP_QT_VERSION }}
          modules: qtmultimedia
          aqtversion: ${{ env.TP_AQT_VERSION }}
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: CMake configuration
        run: |
          mkdir build
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Debug -D CMAKE_PREFIX_PATH=${{ env.Qt6_DIR }}
          
      - name: Build
        run: cmake --build build --target all
