name: windows-2019

on:
  push:
    branches: [ main ]
    paths:
      - '**.yml'
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**.ts'
    
  pull_request:
    branches: [ main ]
    paths:
      - '**.yml'
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '**.ts'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
        
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.0
          modules: qtmultimedia
          aqtversion: '>=3.1.0'
          py7zrversion: '>=0.20.2'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup path for MSVC's cl.exe
        uses: ilammy/msvc-dev-cmd@v1
          
      - name: Conan installation
        run: |
          conan profile detect --force
          
          mkdir build
          
          conan install ./conanfile_ci.txt `
          -of build `
          --build missing `
      
      - name: CMake configuration
        run: |
          cd build
          
          cmake .. -G Ninja `
	  -D CMAKE_BUILD_TYPE=Release `
          -D CMAKE_PREFIX_PATH=${{ env.Qt6_DIR }} `
          -D CMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
          
      - name: Build
        run: cmake --build build
